const tileLayerList = {
  0: "https://tile.openstreetmap.org/{z}/{x}/{y}.png",
  1: "https://tile.openstreetmap.de/{z}/{x}/{y}.png",
  2: "https://tile.osm.ch/switzerland/{z}/{x}/{y}.png",
  3: "https://{s}.tile.openstreetmap.fr/osmfr/{z}/{x}/{y}.png",
  4: "https://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png",
  5: "https://tile.openstreetmap.bzh/br/{z}/{x}/{y}.png",
  6: "https://maptiles.p.rapidapi.com/{variant}/{z}/{x}/{y}.png?rapidapi-key={apikey}",
  7: "https://tiles.openseamap.org/seamark/{z}/{x}/{y}.png",
  8: "https://tileserver.memomaps.de/tilegen/{z}/{x}/{y}.png",
  9: "https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png",
  10: "https://{s}.tiles.openrailwaymap.org/standard/{z}/{x}/{y}.png",
  11: "http://openfiremap.org/hytiles/{z}/{x}/{y}.png",
  12: "https://s3.amazonaws.com/te512.safecast.org/{z}/{x}/{y}.png",
  13: "https://tiles.stadiamaps.com/tiles/{variant}/{z}/{x}/{y}{r}.{ext}",
  14: "https://tiles.stadiamaps.com/tiles/{variant}/{z}/{x}/{y}.{ext}",
  15: "https://{s}.tile.thunderforest.com/{variant}/{z}/{x}/{y}.png?apikey={apikey}",
  16: "https://{s}.tile-cyclosm.openstreetmap.fr/cyclosm/{z}/{x}/{y}.png",
  17: "https://{s}.tile.jawg.io/{variant}/{z}/{x}/{y}{r}.png?access-token={accessToken}",
  18: "https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}{r}?access_token={accessToken}",
  19: "https://api.maptiler.com/maps/{variant}/{z}/{x}/{y}{r}.{ext}?key={key}",
  20: "https://{s}.api.tomtom.com/map/1/tile/{variant}/{style}/{z}/{x}/{y}.{ext}?key={apikey}",
  21: "https://server.arcgisonline.com/ArcGIS/rest/services/{variant}/MapServer/tile/{z}/{y}/{x}",
  22: "http://{s}.tile.openweathermap.org/map/{variant}/{z}/{x}/{y}.png?appid={apiKey}",
  23: "https://{s}.freemap.sk/T/{z}/{x}/{y}.jpeg",
  24: "http://tile.mtbmap.cz/mtbmap_tiles/{z}/{x}/{y}.png",
  25: "https://{s}.basemaps.cartocdn.com/{variant}/{z}/{x}/{y}{r}.png",
  26: "https://tiles.wmflabs.org/{variant}/{z}/{x}/{y}.png",
  27: "https://mapsneu.wien.gv.at/basemap/{variant}/{type}/google3857/{z}/{y}/{x}.{format}",
  28: "https://service.pdok.nl/brt/achtergrondkaart/wmts/v2_0/{variant}/EPSG:3857/{z}/{x}/{y}.png",
  29: "https://map1.vis.earthdata.nasa.gov/wmts-webmerc/{variant}/default/{time}/{tilematrixset}{maxZoom}/{z}/{y}/{x}.{format}",
  30: "https://nls-{s}.tileserver.com/nls/{z}/{x}/{y}.jpg",
  31: "https://www.justicemap.org/tile/{size}/{variant}/{z}/{x}/{y}.png",
  32: "https://www.justicemap.org/tile/{size}/{variant}/{z}/{x}/{y}.png",
  33: "https://wxs.ign.fr/{apikey}/geoportail/wmts?REQUEST=GetTile&SERVICE=WMTS&VERSION=1.0.0&STYLE={style}&TILEMATRIXSET=PM&FORMAT={format}&LAYER={variant}&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}",
  34: "https://maps-{s}.onemap.sg/v3/{variant}/{z}/{x}/{y}.png",
  35: "https://basemap.nationalmap.gov/arcgis/rest/services/USGSTopo/MapServer/tile/{z}/{y}/{x}",
  36: "https://basemap.nationalmap.gov/arcgis/rest/services/USGSImageryOnly/MapServer/tile/{z}/{y}/{x}",
  37: "https://tile.waymarkedtrails.org/{variant}/{z}/{x}/{y}.png",
  38: "https://{s}.tile.maps.openaip.net/geowebcache/service/tms/1.0.0/openaip_basemap@EPSG%3A900913@png/{z}/{x}/{y}.{ext}",
  39: "https://tiles.opensnowmap.org/{variant}/{z}/{x}/{y}.png",
  40: "https://wmts.geo.admin.ch/1.0.0/{variant}/default/current/3857/{z}/{x}/{y}.jpeg",
};

let mapOption = {
  center: L.latLng(35.699444, 51.337776),
  maxZoom: 17,
  ext: "png",
  attribution: "behhhzaadddd",
  layers: [L.tileLayer(tileLayerList[4])],
};

let map = L.map("root", mapOption);
